/* ******************************************************************************/
/*	Oracle DROP script 1 for Base Ninjas- Part 2 Project                			*/
/* ******************************************************************************/

DROP TABLE "EMPLOYEE" CASCADE CONSTRAINTS;
DROP TABLE "ADDRESS" CASCADE CONSTRAINTS;
DROP TABLE "STATE" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT" CASCADE CONSTRAINTS;
DROP TABLE "PROJECTROLE" CASCADE CONSTRAINTS;
DROP TABLE "STATETAX" CASCADE CONSTRAINTS;
DROP TABLE "FEDERALTAX" CASCADE CONSTRAINTS;
DROP TABLE "JOBTYPE" CASCADE CONSTRAINTS;
DROP TABLE "TIMESHEET" CASCADE CONSTRAINTS;
DROP TABLE "PAYPERIOD" CASCADE CONSTRAINTS;
DROP TABLE "EEOCLASSIFICATION" CASCADE CONSTRAINTS;
